import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { AuthProvider } from "@/context/auth/useAuth";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import useColor from "@/hooks/useColor";
import '@ant-design/v5-patch-for-react-19';
import { MessageProvider } from "@/context/socket/useMessage";
import { Suspense } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tarot AI Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { brandPrimaryDark, redError, brandPrimary, brandPrimaryTap } = useColor();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <AuthProvider>
            <MessageProvider>
              <ConfigProvider
                theme={{
                  token: {
                    colorError: redError,
                    colorPrimary: brandPrimary,
                  }
                }}
              >
                <Suspense>
                  {children}
                </Suspense>
              </ConfigProvider>
            </MessageProvider>
          </AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
