export const ENGLocalizedStrings = {
  GLobals: {
    AppName: "TAROT APP",
    ErrorMessage: "Something went wrong, please try again",
    Next: "Next",
    Processing: "Processing...",
    Exit: "Exit",
    Cancel: "Cancel",
    ExitConfirm: "Are you sure you want to exit?",
    Topic: "Topic",
    CreatedDate: "Created date",
    FromDate: "From date",
    ToDate: "To date",
    Apply: "Apply",
    Report: "Report",
    Delete: "Delete",
    DeleteChat: "Are you sure you want to delete this chat?",
    Day: "Day",
    Remain: "Only",
    Confirm: "Confirm",
    RemainDay: "Remain status",
    Opened: "Opened",
    Closed: "Closed",
    All: "All",
    DateRange: "Date range",
    Options: "Options",
    Cards: "Cards",
    Submit: "Submit",
    Logout: "Logout",
    LogoutMessage: "Are you sure you want to logout?",
    Language: "Tiếng Việt",
    Edit: "Edit",
    Success: "Success",
    Failed: "Failed",
  },
  Topics: {
    health: "Health",
    love: "Love",
    finance: "Finance",
    family: "Family",
    career: "Career",
    social: "Social"
  },
  Login: {
    LoginByPhone: "Login by phone",
    LoginByFacebook: "Login by Facebook",
    Phone: "Phone number",
    PhoneInvalid: "Please enter phone number",
    PhoneLengthInvalid: "Phone number must be 10 digits",
    OTP: "OTP",
    OTPInvalid: "Please enter OTP",
    OTPLengthInvalid: "OTP must be 6 digits",
    LoginSuccess: "Login successfully",
    LoginFailed: "Login failed",
    SentOTPSuccess: "Sent OTP successfully",
    SentOTPFailed: "Sent OTP failed",
    OTPVerified: "OTP verified",
    HaveSend: "OTP have been sent: "
  },
  Register: {
    Title: "Register",
    Label: {
      Fullname: "Full name",
      Phone: "Phone number",
      Gender: "Gender",
      Birthday: "Birthday",
      Male: "Male",
      Female: "Female",
    },
    Placeholder: {
      Fullname: "Please enter full name",
      Phone: "Please enter phone number",
      Gender: "Please select gender",
      Birthday: "Please select birthday",
    },
    RegisterFailed: "Register failed",
    RegisterSuccess: "Register successfully",
    Messages: {
      FullnameRequired: "Full name should be at least 3 characters",
      BirthdayRequired: "Birthday should be a valid date",
      GenderRequired: "Gender should be male or female",
    }
  },
  History: {
    GetListChatFailed: "Get list chat failed",
    FindText: "Find text...",
  },
  Chat: {
    EnterMessage: "Enter message...",
    GetListMessageFailed: "Get list message failed",
    DeleteChatFailed: "Delete chat failed",
    DeleteChatSuccess: "Delete chat successfully",
  },
  Create: {
    ChooseTopic: "Choose a topic",
    Question: "Question",
    QuestionPlaceholder: "Please enter a question...",
    Now: "Watch now with "
  },
  Horoscope: {
    Title: "Daily Horoscope",
    Today: "Today's horoscope",
    InterpretingDestiny: "Interpreting Destiny",
    Love: "Love",
    Finance: "Finance",
    Career: "Career",
    Health: "Health",
    Luck: "Luck",
    LuckyNumber: "Lucky number",
    LuckyColor: "Lucky color",
  },
  Cards: {
    PickingCards: "Pick cards",
    PickingNote: "Think about your question, choose 3 cards, and tap on the card slot."
  },
  Tabbar: {
    Home: "Home",
    Profile: "Profile",
    History: "Chat",
    Notification: "Notification",
  },
  Profile: {
    Title: "My profile",
    Point: "Points",
    PointNote: "Accumulated points for using services",
    TransHistory: "Transaction History",
    TransHistoryNote: "Records of point changes",
    Horoscope: "Daily Message",
    HoroscopeNote: "Your cosmic messages from the past 3 days",
  },
  Setting: {
    Title: "Settings",
    UpdateProfileSuccess: "Update profile successfully",
    UpdateProfileFailed: "Update profile failed",
  },
  Topup: {
    Title: "Point packages",
    GetListPackageFailed: "Get list package failed",
    Pay: "Pay",
    CreateBillFailed: "Pay failed",
    CreateBillSuccess: "Pay successfully",
  },
  Transaction: {
    GetListBillFailed: "Get list bill failed",
    Package: "Packages",
    Point: "Points",
    TopupPoint: "Top up points",
  }
}
