export const VnLocalizedStrings = {
  GLobals: {
    AppName: "TAROT APP",
    ErrorMessage: "Đã có lỗi xảy ra, vui lòng thử lại",
    Next: "Tiếp tục",
    Processing: "Đang xử lý...",
    Exit: "Thoát",
    Cancel: "Hủy",
    ExitConfirm: "Bạn có chắc muốn thoát?",
    Topic: "Chủ đề",
    CreatedDate: "Ngày tạo",
    FromDate: "Từ ngày",
    ToDate: "Đến ngày",
    Apply: "Áp dụng",
    Report: "Báo cáo",
    Delete: "Xóa",
    DeleteChat: "Bạn có muốn xóa đoạn chat này?",
    Day: "Ngày",
    Remain: "Còn",
    Confirm: "Xác nhận",
    RemainDay: "Thời hạn tin",
    Opened: "Còn mở",
    Closed: "Đã đóng",
    All: "Tất cả",
    DateRange: "Khoảng ngày",
    Options: "Tùy chọn",
    Cards: "Lá bài",
    Submit: "Xác nhận",
    Logout: "Đăng xuất",
    LogoutMessage: "Bạn có chắc muốn đăng xuất tài khoản này?",
    Language: "English",
    Edit: "Chỉnh sửa",
    Success: "Thành công",
    Failed: "Thất bại",
  },
  Topics: {
    health: "Sức khỏe",
    love: "Tình yêu",
    finance: "Tài chính",
    family: "Gia đình",
    career: "Sự nghiệp",
    social: "Xã hội"
  },
  Login: {
    LoginByPhone: "Đăng nhập bằng SĐT",
    LoginByFacebook: "Đăng nhập bằng Facebook",
    Phone: "Số điện thoại",
    PhoneInvalid: "Vui lòng nhập số điện thoại",
    PhoneLengthInvalid: "Số điện thoại phải đủ 10 số",
    OTP: "Mã OTP",
    OTPInvalid: "Vui lòng nhập mã OTP",
    OTPLengthInvalid: "Mã OTP phải đủ 6 số",
    LoginSuccess: "Đăng nhập thành công",
    LoginFailed: "Đăng nhập thất bại",
    SentOTPSuccess: "Đã gửi mã OTP",
    SentOTPFailed: "Gửi OTP thất bại",
    OTPVerified: "Xác nhận mã OTP thành công",
    HaveSend: "Đã gửi tới: "
  },
  Register: {
    Title: "Đăng ký",
    Label: {
      Fullname: "Họ và tên",
      Phone: "Số điện thoại",
      Gender: "Giới tính",
      Birthday: "Ngày sinh",
      Male: "Nam",
      Female: "Nữ",
    },
    Placeholder: {
      Fullname: "Vui lòng nhập họ và tên",
      Phone: "Vui lòng nhập số điện thoại",
      Gender: "Vui lòng nhập giới tính",
      Birthday: "Vui lòng nhập ngày sinh",
    },
    RegisterFailed: "Đăng ký thất bại",
    RegisterSuccess: "Đăng ký thành công",
    Messages: {
      FullnameRequired: "Họ tên phải có ít nhất 3 ký tự",
      BirthdayRequired: "Ngày sinh phải là ngày quá khứ",
      GenderRequired: "Giới tính phải là nam hoặc nữ",
    }
  },
  History: {
    GetListChatFailed: "Lỗi lấy danh sách chat",
    FindText: "Tìm kiếm tin nhắn...",
  },
  Chat: {
    EnterMessage: "Nhập tin nhắn...",
    GetListMessageFailed: "Lỗi lấy danh sách tin nhắn",
    DeleteChatFailed: "Xóa tin nhắn thất bại",
    DeleteChatSuccess: "Xóa tin nhắn thành công",
  },
  Create: {
    ChooseTopic: "Chọn chủ đề",
    Question: "Câu hỏi",
    QuestionPlaceholder: "Nhập câu hỏi...",
    Now: "Xem ngay với "
  },
  Horoscope: {
    Title: "Thông điệp hằng ngày",
    Today: "Thông điệp hôm nay",
    InterpretingDestiny: "Giải đoán vận mệnh",
    Love: "Tình yêu",
    Finance: "Tài chính",
    Career: "Sự nghiệp",
    Health: "Sức khỏe",
    Luck: "Vận may",
    LuckyNumber: "Số may mắn",
    LuckyColor: "Màu may mắn",
  },
  Cards: {
    PickingCards: "Bốc bài",
    PickingNote: "Hãy nghĩ về câu hỏi, chọn 3 lá bài và bấm vào ô bài.",
  },
  Tabbar: {
    Home: "Trang chủ",
    Profile: "Tôi",
    History: "Trò chuyện",
    Notification: "Thông báo",
  },
  Profile: {
    Title: "Trang cá nhân",
    Point: "Điểm",
    PointNote: "Điểm tích lũy để sử dụng các dịch vụ",
    TransHistory: "Lịch sử giao dịch",
    TransHistoryNote: "Lưu lại lịch sử biến động điểm",
    Horoscope: "Thông điệp hằng ngày",
    HoroscopeNote: "Thông điệp vũ trụ 3 ngày vừa qua của bạn",
  },
  Setting: {
    Title: "Cài đặt",
    UpdateProfileSuccess: "Cập nhật thông tin thành công",
    UpdateProfileFailed: "Cập nhật thông tin thất bại",
  },
  Topup: {
    Title: "Gói điểm",
    GetListPackageFailed: "Lấy danh sách gói thất bại",
    Pay: "Thanh toán",
    CreateBillFailed: "Thanh toán thất bại",
    CreateBillSuccess: "Thanh toán thành công",
  },
  Transaction: {
    GetListBillFailed: "Lấy danh sách thất bại",
    Package: "Gói điểm",
    Point: "Điểm",
    TopupPoint: "Nạp điểm",
  }
};
